'use strict';

const FBR_BASE = {
  DI:        'https://gw.fbr.gov.pk/di_data/v1/di',
  REFERENCE: 'https://gw.fbr.gov.pk/pdi',
  STATL:     'https://gw.fbr.gov.pk/dist',
};

const FBR_URLS = {
  POST_INVOICE_SB:     `${FBR_BASE.DI}/postinvoicedata_sb`,
  POST_INVOICE:        `${FBR_BASE.DI}/postinvoicedata`,
  VALIDATE_INVOICE_SB: `${FBR_BASE.DI}/validateinvoicedata_sb`,
  VALIDATE_INVOICE:    `${FBR_BASE.DI}/validateinvoicedata`,

  PROVINCES:         `${FBR_BASE.REFERENCE}/v1/provinces`,
  DOC_TYPES:         `${FBR_BASE.REFERENCE}/v1/doctypecode`,
  ITEM_CODES:        `${FBR_BASE.REFERENCE}/v1/itemdesccode`,
  SRO_ITEM_CODE:     `${FBR_BASE.REFERENCE}/v1/sroitemcode`,
  TRANS_TYPES:       `${FBR_BASE.REFERENCE}/v1/transtypecode`,
  UOM:               `${FBR_BASE.REFERENCE}/v1/uom`,
  SRO_SCHEDULE:      `${FBR_BASE.REFERENCE}/v1/SroSchedule`,
  SALE_TYPE_TO_RATE: `${FBR_BASE.REFERENCE}/v2/SaleTypeToRate`,
  HS_UOM:            `${FBR_BASE.REFERENCE}/v2/HS_UOM`,
  SRO_ITEM:          `${FBR_BASE.REFERENCE}/v2/SROItem`,

  STATL:        `${FBR_BASE.STATL}/v1/statl`,
  GET_REG_TYPE: `${FBR_BASE.STATL}/v1/Get_Reg_Type`,
};

const SCENARIOS = [
  { id: 'SN001', label: 'SN001 – Goods at standard rate to registered buyers' },
  { id: 'SN002', label: 'SN002 – Goods at standard rate to unregistered buyers' },
  { id: 'SN003', label: 'SN003 – Sale of Steel (Melted and Re-Rolled)' },
  { id: 'SN004', label: 'SN004 – Sale by Ship Breakers' },
  { id: 'SN005', label: 'SN005 – Reduced rate sale' },
  { id: 'SN006', label: 'SN006 – Exempt goods sale' },
  { id: 'SN007', label: 'SN007 – Zero rated sale' },
  { id: 'SN008', label: 'SN008 – Sale of 3rd schedule goods' },
  { id: 'SN009', label: 'SN009 – Cotton Spinners purchase from Cotton Ginners' },
  { id: 'SN010', label: 'SN010 – Telecom services rendered or provided' },
  { id: 'SN011', label: 'SN011 – Toll Manufacturing sale by Steel sector' },
  { id: 'SN012', label: 'SN012 – Sale of Petroleum products' },
  { id: 'SN013', label: 'SN013 – Electricity Supply to Retailers' },
  { id: 'SN014', label: 'SN014 – Sale of Gas to CNG stations' },
  { id: 'SN015', label: 'SN015 – Sale of mobile phones' },
  { id: 'SN016', label: 'SN016 – Processing / Conversion of Goods' },
  { id: 'SN017', label: 'SN017 – Sale of Goods where FED is charged in ST mode' },
  { id: 'SN018', label: 'SN018 – Services where FED is charged in ST mode' },
  { id: 'SN019', label: 'SN019 – Services rendered or provided' },
  { id: 'SN020', label: 'SN020 – Sale of Electric Vehicles' },
  { id: 'SN021', label: 'SN021 – Sale of Cement / Concrete Block' },
  { id: 'SN022', label: 'SN022 – Sale of Potassium Chlorate' },
  { id: 'SN023', label: 'SN023 – Sale of CNG' },
  { id: 'SN024', label: 'SN024 – Goods listed in SRO 297(1)/2023' },
  { id: 'SN025', label: 'SN025 – Drugs at fixed ST rate (8th Schedule Table 1 serial 81)' },
  { id: 'SN026', label: 'SN026 – Sale to End Consumer by retailers (Standard Rate)' },
  { id: 'SN027', label: 'SN027 – Sale to End Consumer by retailers (3rd Schedule)' },
  { id: 'SN028', label: 'SN028 – Sale to End Consumer by retailers (Reduced Rate)' },
];

const SALE_TYPES = [
  'Goods at Standard Rate (default)',
  'Steel Melting and re-rolling',
  'Ship breaking',
  'Goods at Reduced Rate',
  'Exempt Goods',
  'Goods at zero-rate',
  '3rd Schedule Goods',
  'Cotton Ginners',
  'Telecommunication services',
  'Toll Manufacturing',
  'Petroleum Products',
  'Electricity Supply to Retailers',
  'Gas to CNG stations',
  'Mobile Phones',
  'Processing/ Conversion of Goods',
  'Goods (FED in ST Mode)',
  'Services (FED in ST Mode)',
  'Services',
  'Electric Vehicle',
  'Cement /Concrete Block',
  'Potassium Chlorate',
  'CNG Sales',
  'Goods as per SRO.297(|)/2023',
  'Non-Adjustable Supplies',
];

const SALES_ERROR_CODES = {
  '0001': 'Seller not registered for sales tax.',
  '0002': 'Invalid Buyer Registration No or NTN (must be 13-digit CNIC or 7/9-digit NTN).',
  '0003': 'Provide proper invoice type.',
  '0005': 'Invoice date must be in YYYY-MM-DD format.',
  '0006': 'Sale invoice does not exist against STWH.',
  '0007': 'Wrong Sale type selected for this registration number.',
  '0008': 'ST withheld at source must be zero or equal to Sales Tax.',
  '0009': 'Provide Buyer Registration No.',
  '0010': 'Provide Buyer Name.',
  '0011': 'Provide invoice type.',
  '0012': 'Provide valid Buyer Registration Type.',
  '0013': 'Provide valid Sale type.',
  '0018': 'Please provide Sales Tax/FED in ST Mode.',
  '0019': 'Please provide HSCode.',
  '0020': 'Please provide Rate.',
  '0021': 'Please provide Value of Sales Excl. ST / Quantity.',
  '0022': 'Please provide ST withheld at Source or STS Withheld.',
  '0023': 'Please provide Sales Tax.',
  '0024': 'Please provide ST withheld.',
  '0026': 'Invoice Reference No. is required (debit/credit notes).',
  '0027': 'Reason is required (debit/credit notes).',
  '0028': 'Reason Remarks required when reason is "Others".',
  '0029': 'Invoice date must be >= original invoice date.',
  '0030': 'Unregistered distributor type not allowed before cut-off date.',
  '0031': 'Provide Sales Tax.',
  '0032': 'STWH can only be created for GOV/FTN Holders.',
  '0034': 'Debit/Credit note only allowed within 180 days of original invoice.',
  '0035': 'Note date must be >= original invoice date.',
  '0036': 'Credit Note: Value of Sales must be <= original invoice.',
  '0037': 'Credit Note: ST Withheld must be <= original invoice.',
  '0039': 'STWH invoice fields must match the sale invoice (registered users).',
  '0041': 'Provide invoice No.',
  '0042': 'Provide invoice date.',
  '0043': 'Provide valid Date.',
  '0044': 'Provide HS Code.',
  '0046': 'Provide rate.',
  '0050': 'Cotton Ginners: Sales Tax Withheld must equal Sales Tax or zero.',
  '0052': 'HS Code does not match provided sale type.',
  '0053': 'Buyer registration type is invalid.',
  '0055': 'Provide ST Withheld as WH Agent.',
  '0056': 'Buyer does not exist in steel sector.',
  '0057': 'Reference Invoice does not exist.',
  '0058': 'Self-invoicing not allowed (buyer and seller NTN are the same).',
  '0064': 'Credit note already added to this invoice.',
  '0067': 'Sales Tax of Debit Note > original invoice.',
  '0068': 'Sales Tax of Credit Note < original invoice.',
  '0070': 'STWH cannot be created for unregistered buyers.',
  '0071': 'Credit note only allowed for specific users.',
  '0073': 'Provide Sale Origination Province of Supplier.',
  '0074': 'Provide Destination of Supply.',
  '0077': 'Provide SRO/Schedule No.',
  '0078': 'Provide Item Sr. No.',
  '0079': 'If sales value > 20,000, rate 5% is not allowed.',
  '0080': 'Please provide Further Tax.',
  '0081': 'Please provide Input Credit not Allowed.',
  '0082': 'Seller is not registered for sales tax.',
  '0083': 'Mismatch Seller Registration No.',
  '0085': 'Please provide Total Value of Sales (PFAD only).',
  '0086': 'Not an EFS license holder who imported Compressor Scrap in last 12 months.',
  '0087': 'Petroleum Levy rates not configured properly.',
  '0088': 'Invoice number must be alphanumeric, hyphens allowed (e.g. Inv-001).',
  '0089': 'Please provide FED Charged.',
  '0090': 'Please provide Fixed/notified value or Retail Price.',
  '0091': 'Extra tax must be empty.',
  '0092': 'Provide Valid Sale Type.',
  '0093': 'Selected Sale Type not allowed for Manufacturer.',
  '0095': 'Please provide Extra Tax.',
  '0096': 'For this HS Code, only KWH UOM is allowed.',
  '0097': 'Provide UOM in KG.',
  '0098': 'Please provide Quantity / Electricity Units.',
  '0099': 'UOM must match the given HS Code.',
  '0100': 'Cotton Ginners only allowed against registered buyers.',
  '0101': 'Use Toll Manufacturing Sale Type for Steel Sector.',
  '0102': 'Calculated tax does not match 3rd schedule formula.',
  '0103': 'Calculated tax for Potassium Chlorate does not match.',
  '0104': 'Calculated percentage sales tax does not match.',
  '0105': 'Calculated sales tax for the quantity is incorrect.',
  '0106': 'Buyer is not registered for sales tax.',
  '0107': 'Mismatch Buyer Registration No.',
  '0108': 'Invalid Seller Registration No or NTN.',
  '0109': 'Wrong invoice type selected.',
  '0111': 'Wrong purchase type selected.',
  '0113': 'Date not in proper format — use YYYY-MM-DD.',
  '0300': 'Provided decimal value is not valid at field.',
  '0401': 'Seller NTN/CNIC does not have a valid or authorized access token.',
  '0402': 'Buyer NTN/CNIC does not have a valid or authorized access token.',
};

const PURCHASE_ERROR_CODES = {
  '0156': 'Invalid NTN / Reg No. provided.',
  '0157': 'Buyer is not registered for sales tax.',
  '0158': 'Mismatch Buyer Registration No.',
  '0159': 'FTN holder as seller not allowed for purchases.',
  '0160': 'Provide Buyer Name.',
  '0161': 'Invoice Date must be >= original sale invoice date.',
  '0162': 'Provide Sale Type.',
  '0163': 'Selected Sale Type not allowed for Manufacturer.',
  '0164': 'For this HS Code, only KWH UOM is allowed.',
  '0165': 'Provide UOM in KG.',
  '0166': 'Please provide Quantity / Electricity Units.',
  '0167': 'Provide Value of Sales Excl. ST.',
  '0168': 'Cotton Ginners only allowed against registered buyers.',
  '0169': 'STWH only for GOV/FTN Holders.',
  '0170': 'If Value of Sales Excl. ST > 20,000, rate 5% not allowed.',
  '0171': 'Not an EFS license holder who imported Compressor Scrap in last 12 months.',
  '0172': 'Petroleum Levy rates not configured properly.',
  '0173': 'Invoice number must be alphanumeric with optional hyphens.',
  '0174': 'Please provide Sales Tax.',
  '0175': 'Please provide Fixed/notified value or Retail Price.',
  '0176': 'Please provide ST withheld at Source.',
  '0177': 'Please provide Further Tax.',
};

module.exports = { FBR_URLS, SCENARIOS, SALE_TYPES, SALES_ERROR_CODES, PURCHASE_ERROR_CODES };
